### ISSUE TITLE
Error:Default reported if no StopLoss used

### ISSUE THREAD

**Issue by sf52crypto** [Effanuel/BitMEX-scaled-orders#6]
Submitting orders without stoploss produces an error.  I've had to submit with a stoploss and then remove/modify it to avoid the error.

**Comment by Effanuel** [comment]
* Fixed on [v1.5.6](https://github.com/Effanuel/BitMEX-scaled-orders/releases/tag/v1.5.6) release.

Thanks.

**Comment by Effanuel** [comment]
I forgot to update a version ticker, so every time you clone master or a new release. make sure to check the title of the tab, to match the version. Due to the service worker, you may need to reload the page a few times. v1.5.6 will still show v1.5.5.
I need to make updating version a habit from now on.
